### ISSUE TITLE
XAC says "Loading..." forever after host add auth error

### ISSUE THREAD

**Issue by mcclurmc** [HPieters/xac.js#4]
![xac_auth_bug](https://f.cloud.github.com/assets/470276/1057913/467d8d94-117e-11e3-8de8-11ecccdbad43.png)

I try to add a host with a bad username, and XAC remains on the "Loading..." window indefinitely.

**Comment by lucacalcaterra** [comment]
I've the same issue...

**Comment by HPieters** [comment]
Thank you for your interest in this project @lucacalcaterra, however I am afraid the project has been long abandoned. I would recommend you take a look at Xen Orchestra (https://github.com/vatesfr/xo) which is still in active development.
